tackle-123-copy-assessment-between-2-apps
konveyor/tackle-pathfinder pull request #37
Opened 2021-04-21 14:42 UTC by jonathanvila

Signed-off-by: Jonathan Vila <jvilalop@redhat.com>

2021-04-22 08:43 UTC, carlosthe19916 commented
@jonathanvila @m-brophy my two cents:
- For starting a copy the target and source data is being inserted through QueryParams. https://github.com/konveyor/tackle-pathfinder/blob/170dc8edb2ad3a62fcfeaccd9e29eb729c524b7d/src/main/java/io/tackle/pathfinder/controllers/AssessmentsResource.java#L75 
My opinion is that in POST/PUT operations we should be consistent with the rest of the endpoints and pass the data within the body and not through QueryParams. Technically nothing stops us from using QueryParams but I think we should have at least basic standards. The standard I propose is `use queryParams` if they are optional values,  `use the body or pathParams` if the data is mandatory. Wdyt? 
- For copying an assessment the current PR is using `targetApplicationId and sourceApplicationId` but I think what we should send to the backend is `targetAssessmentId and sourceApplicationIds` using `/POST /assessments/{targetAssessmentId}/copy` and within the body of the request we should send the list of applicationIds we want to copy the assessment. e.g:
```
POST /assessments/1
{
 applicationIdSource: [1,2,3,4,5,6]
}
```
Of course for the current PR we should only copy assessments one by one but for the future, I think we should copy multiple assessments.

2021-04-23 14:04 UTC, m-brophy requested changes

2021-04-26 08:19 UTC, jonathanvila commented
>   My opinion is that in POST/PUT operations we should be consistent with the rest of the endpoints and pass the data within the body and not through QueryParams. Technically nothing stops us from using QueryParams but I think we should have at least basic standards. The standard I propose is `use queryParams` if they are optional values,  `use the body or pathParams` if the data is mandatory. Wdyt?

I would say Queryparams can be used when are not part of an entity to be stored. Optional/Mandatory should be the criteria to use query params in my opinion. 
Few criterias : 
* if you talk about 2,3 fields then Querystring could be a good place
* if you are sending DATA (not params) it should go in the body
* if you are sending parameters that configure an opperation, querystring could be a good place
* 
Here there are few links that can support current approach : 
https://stackoverflow.com/questions/25385559/rest-api-best-practices-args-in-query-string-vs-in-request-body
https://www.moesif.com/blog/technical/api-design/REST-API-Design-Best-Practices-for-Parameters-and-Query-String-Usage/

Obviously everything is opinionable in API design.

2021-04-26 08:24 UTC, jonathanvila commented
> * For copying an assessment the current PR is using `sourceApplicationId and targetApplicationId` but I think what we should send to the backend is `sourceAssessmentId and targetApplicationIds` using `/POST /assessments/{sourceAssessmentId}/copy` and within the body of the request we should send the list of applicationIds we want to copy the assessment to. e.g:
> 
> ```
> POST /assessments/1/copy
> {
>  applicationIdTarget: [1,2,3,4,5,6]
> }
> ```
> 
> Of course for the current PR we should only copy assessments one by one but for the future, I think we should copy multiple assessments.

The current scope for this PR is copying one by one. There's another Ticket to cover the bulk copy, that will need a little discussion to cover ( https://github.com/konveyor/tackle-pathfinder/issues/38 ) : 
* sync or async , as it can take long to copy to several apps
* response as a list with status for each target app, as it could happen a subgroup of target apps fails , due to they already have an assessment, process exceptions, etc.

Appartfrom that the url you are proposing is copying an assessment NOT an application. If the application has more elements inside the operation is intended to copy everything not an assessment alone.
The right way to do it would be : /application/1234/copy

2021-04-26 08:50 UTC, jonathanvila commented on src/main/java/io/tackle/pathfinder/services/AssessmentSvc.java
> +                                                .questionnaire(sourceAssessment.assessmentQuestionnaire.questionnaire)
In fact I've seen there's no such field on the Questionnaire to store the assessmentQuestionnaires.

2021-04-26 10:06 UTC, jonathanvila commented on src/main/java/io/tackle/pathfinder/services/AssessmentSvc.java
> +                                                .questionnaire(sourceAssessment.assessmentQuestionnaire.questionnaire)
So no need to add to questionnaire.

2021-04-26 14:10 UTC, m-brophy commented
My comments have all been addressed satisfactorily so when you are happy @carlosthe19916 can you merge this PR?

2021-04-27 09:34 UTC, merged