Tackle-9 Get Assessment Multilanguage support
konveyor/tackle-pathfinder pull request #80
Opened 2021-07-02 09:53 UTC by jonathanvila

Issue :

Added capability to return a translated Assessment on GetAssessment endpoint,  regarding : 
* category name
* question name and description
* option name

User comments are not translated.

2021-07-12 14:59 UTC, m-brophy requested changes

2021-07-12 14:59 UTC, m-brophy commented on src/main/java/io/tackle/pathfinder/controllers/AssessmentsResource.java
> +  public List<RiskLineDto> getIdentifiedRisks(@NotNull @Valid List<ApplicationDto> applicationList, @QueryParam("language") String language) {
language parameter isn't used

2021-07-12 14:59 UTC, m-brophy commented on src/test/java/io/tackle/pathfinder/controllers/AssessmentsResourceTest.java
> +				@ResourceArg(name = KeycloakTestResource.IMAGE_TAG, value = "latest")
is this image_tag parameter needed?

2021-07-12 14:59 UTC, m-brophy commented on src/test/java/io/tackle/pathfinder/services/TranslatorSvcTest.java
> +        // Checking a language not existing, should give the original texts
comment needs to be updated to match code

2021-07-12 16:22 UTC, jonathanvila commented on .github/workflows/test-minikube.yaml
> +          start args: ' --force --addons=ingress --cpus 2 --memory 6000'
:+1 removing it.

2021-07-12 16:30 UTC, jonathanvila commented on src/main/java/io/tackle/pathfinder/controllers/AssessmentsResource.java
> +  public List<RiskLineDto> getIdentifiedRisks(@NotNull @Valid List<ApplicationDto> applicationList, @QueryParam("language") String language) {
:+1: good catch

2021-07-12 17:00 UTC, jonathanvila commented on src/test/java/io/tackle/pathfinder/controllers/AssessmentsResourceTest.java
> +				@ResourceArg(name = KeycloakTestResource.IMAGE_TAG, value = "latest")
:+1:

2021-07-13 16:11 UTC, m-brophy approved these changes

2021-07-14 08:52 UTC, merged